@startuml
skinparam shadowing false

|Comercial|
start
:Accede a la oportunidad;
:Selecciona cerrar oportunidad;
:Indica el resultado del cierre;

if (\n¿La oportunidad se cierra \ncomo ganada?\n) then (no)

  |Comercial|
  :Selecciona Perdida o \nNo viable;
  :Registra el motivo \ndel cierre;

  |Sistema|
  :Actualiza el estado a\nPerdida o No viable;
  :Guarda el motivo\n del cierre;

  |Comercial|
  :Oportunidad cerrada\nsin generar una orden\nde servicio;

else (sí)

  |Sistema|
  :Actualiza el estado \nde la oportunidad \na Ganada;
  :Recupera los datos \ndel cliente,\ndel servicio, \ny de la propuesta;
  :Genera la orden \nde servicio;
  :Guarda la orden \nasociada a la \noportunidad;

  |Comercial|
  :Revisa la orden de servicio;

  if (¿Exporta la orden?) then (sí)
    |Sistema|
    :Genera el archivo \nexportable;
    |Comercial|
    :Descarga la orden de servicio;
  else (no)
  endif

  :Orden disponible para su\ntraspaso a operaciones;


endif

stop
@enduml