@startuml

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 100

hide circle
hide members

class Usuario
class Lead
class Cliente
class Contacto
class Oportunidad
class "Historial de seguimiento" as HistorialSeguimiento
class "Orden de servicio" as OrdenServicio
class Propuesta
class "Solicitud de servicio" as SolicitudServicio
class Cotizacion
class "Ítem de cotización" as ItemCotizacion
class "Ítem de servicio solicitado" as ItemServicioSolicitado
class Residuo
class "Tarifa base" as TarifaBase

Usuario -right-> Lead : registra
Lead -right-> Cliente : se vincula a
Cliente "1" -right-> "1..*" Contacto 

Lead "1" -down-> "0..*" Oportunidad : origina
Cliente "0..1" -down-> "0..*" Oportunidad : se asocia a
Usuario "1" -down-> "0..*" Oportunidad : gestiona

Oportunidad "1" -left-> "0..*" HistorialSeguimiento : registra
Oportunidad "1" -right-> "0..1" OrdenServicio : genera

Oportunidad "1" -down-> "0..*" Propuesta
Oportunidad "1" -down-> "1" SolicitudServicio

SolicitudServicio "1" -down-> "1..*" ItemServicioSolicitado
SolicitudServicio "1" -right-> "0..*" Cotizacion : origina

Cotizacion "1" -down-> "1..*" ItemCotizacion
Cotizacion "1" -right-> "1" Propuesta : base para

ItemCotizacion "0..*" .left.> "1" ItemServicioSolicitado : referencia
ItemCotizacion "0..*" .down.> "1" TarifaBase : usa tarifa
ItemServicioSolicitado "0..*" -down-> "1" Residuo
Residuo "1" -right-> "0..*" TarifaBase : dispone de

@enduml